### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by narrowtux** [herenowcoder/eastar#2]
I'm getting a compile error with this environment:

Elixir: 1.3.1
Erlang: 18
eastar: 0.4.0

This is the console output of the error:

```
== Compilation error on file lib/heapmap.ex ==
** (UndefinedFunctionError) function :with.__struct__/1 is undefined (module :with is not available)
    :with.__struct__({:with, [], [{:<-, [], [{:when, [], [{{:_, [], Kernel}, {:doc, [counter: -576460752303423179], Kernel}}, false]}, {{:., [], [{:__aliases__, [alias: false, counter: -576460752303423179], [:Module]}, :get_attribute]}, [], [{:__MODULE__, [counter: -576460752303423179], Kernel}, :h, [{:{}, [], [Astar.HeapMap, :__MODULE__, 0, [file: "lib/heapmap.ex", line: 9]]}]]}]}, [do: {:doc, [counter: -576460752303423179], Kernel}]]})
    (elixir) Kernel.Typespec.typespec/3
    (elixir) lib/kernel/typespec.ex:390: Kernel.Typespec.translate_type/3
    lib/heapmap.ex:1: (file)
```

**Comment by wkhere** [comment]
Yeah, probably the typespec format has been changed - this is wildguessing from the error above.

I haven't put my hands on Elixir 1.3 yet. Also my CI [is not using it](https://github.com/herenowcoder/eastar/blob/ba8b34/circle.yml#L4).

So as a temp measure I'm restricting Elixir to 1.2 - this went to Eastar 0.4.1 on Hex.

Does it bring you any trouble?

**Comment by narrowtux** [comment]
I was just evaluating the library for now but I definitely need elixir 1.3 now

**Comment by herenowcoder** [comment]
Feel free to patch it, then! :]

**Comment by wkhere** [comment]
Wow, thx @narrowtux !!
